export const APP_PAGE_META = {
  access: { title: 'Команда', subtitle: 'Участники, роли и доступы' },
  applications: { title: 'Приложения', subtitle: 'Задеплоенные сервисы и их адреса' },
  billing: { title: 'Биллинг', subtitle: 'Счета, оплата и выгрузка для 1С' },
  dashboard: { title: 'Обзор', subtitle: 'Проекты, приложения и последние деплои' },
  deployments: { title: 'Деплои', subtitle: 'История сборок и логи публикации' },
  documents: { title: 'Документы', subtitle: 'Счета для юрлиц из биллинга' },
  domains: { title: 'Домены', subtitle: 'Адреса платформы и приложений' },
  login: { title: 'Вход', subtitle: '' },
  logs: { title: 'Логи', subtitle: 'История деплоев и фрагменты сборки' },
  projectDetails: { title: 'Проект', subtitle: '' },
  projects: { title: 'Проекты', subtitle: 'Git-репозитории и деплой frontend/backend' },
  serviceDetails: { title: 'Приложение', subtitle: '' },
  settings: { title: 'Настройки', subtitle: 'Профиль, домены и юрлицо' },
  team: { title: 'Команда', subtitle: 'Участники, роли и приглашения' },
} as const;
